### ISSUE TITLE
[BUG] Battle hacks do not work on arena

### ISSUE THREAD

**Issue by Undefineduser2** [Prodigy-Hacking/ProdigyMathGameHacking#1163]
***Description***:
I can't win battle, or use easy mode etc.

***Replication***:

***Images***:
No images available

***Additional Errors***:

**Comment by ArcerionDev** [comment]
unfortunately hacks in arena are not yet possible.

**Comment by 32n** [comment]
Can you give us more details on what exactly isn't working? Do you get any errors in console? What does the toast notif say? Can you reproduce this bug every time?

I've actually sometimes had some of the battle hacks not work because it doesn't recognize me as in a battle, and other ones are straight up broken in all cases.

**Comment by 32n** [comment]
oh wait I am dumb lmao ok thx daddy arc
