### ISSUE TITLE
Make WCM for mobile browsers

### ISSUE THREAD

**Issue by elikiller** [Prodigy-Hacking/ProdigyMathGameHacking#607]
You guys should do this cos myself and many more are trying to use the hacks on mobile browsers but bookmarklets nor address bars are working.
And most of these people can’t install apps like inspect browser so we could use the hacks because we have school devices!!!!!!!!
Pls pls pls make this.🥺

**Comment by elikiller** [comment]
I also asked PixelMMO if it would work and he said yes so why haven’t you done this already?

**Comment by PatheticMustan** [comment]
#600

**Comment by CyberXVI** [comment]
xx

**Comment by PatheticMustan** [comment]
> I also asked PixelMMO if it would work and he said yes so why haven’t you done this already?

PixelMMO isn't staff.

Unfortunately, there are many things that stop us from making such a thing.
A. Prodigy hides all their player objects. In order to expose them, we need to modify the game files.
B. Will's Cheat Menu relies heavily on those player objects being there. Without them, it's just a bunch of buttons.
C. While some hacks are still possible (see script based hacks), they're restricted heavily. Due to Prodigy updating constantly, they're also more burdensome to maintain, and harder to make.

**Comment by NameIsA** [comment]
Mobile Tampermonkey exsists.

**Comment by PatheticMustan** [comment]
Well sure, but we would still need to do a lot of work. We rely heavily on the permissions chrome extensions give us, I'm not sure mobile tampermonkey can do the same thing.

**Comment by NameIsA** [comment]
> Well sure, but we would still need to do a lot of work. We rely heavily on the permissions chrome extensions give us, I'm not sure mobile tampermonkey can do the same thing.

Might be able to. Also the possibility of being able to create/modify accounts via a website.
