### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Oreofurret** [Prodigy-Hacking/ProdigyMathGameHacking#875]
Uhhhh so basically the mods bugging and wont let me turn off uwu mode pls help

**Comment by ArcerionDev** [comment]
have you tried reloading

**Comment by YamaHacks** [comment]
LMAOOO

Delete and reinstall the extension

**Comment by UntrustableRus** [comment]
Follow format, title the issue, fix to the issue has been replied, which is to reload, and there is no way they are still playing prodigy and haven't reloaded. Closed.

**Comment by nickthetrick223** [comment]
Not loading Sent from Mail for Windows 10 From: RusSent: Sunday, April 25, 2021 9:53 PMTo: Prodigy-Hacking/ProdigyMathGameHackingCc: SubscribedSubject: Re: [Prodigy-Hacking/ProdigyMathGameHacking] [BUG] (#875) Closed #875.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
